import type { ToolContent } from '../types';

const updated = '2026-10-07';
const parent = 'electricity-cost-calculator';
const engine = 'electricity-cost-calculator';

export const energyTools: ToolContent[] = [
  {
    slug: 'electricity-cost-calculator', name: 'Electricity Cost Calculator', category: 'energy', popular: true, updated,
    title: 'Electricity Cost Calculator – Appliance Running Cost',
    description: 'Calculate what any appliance costs to run per hour, day, month and year from its wattage, hours of use and your price per kWh. Any currency.',
    lead: 'Find out what any appliance really costs to run — per hour, day, month and year — from its wattage and your electricity rate.',
    keywords: ['electricity bill', 'kwh cost', 'running cost', 'watts to kwh', 'energy cost', 'power consumption', 'how much electricity does it use', 'appliance'],
    about: [
      'Your bill charges for energy in kilowatt-hours (kWh). One kWh is 1,000 watts used for one hour, so a 2,000 W heater running for 30 minutes uses 1 kWh. Multiply by your price per kWh and you have the cost.',
      'The wattage on a label is the maximum draw. Appliances with a compressor or thermostat — fridges, air conditioners, heaters — switch on and off, so they average well below that. Use the “average load” field to reflect this; the appliance pages below have realistic starting values.',
      'Your price per kWh is on your bill. If your tariff has peak and off-peak rates, run the calculation once for each period.',
    ],
    howTo: ['Find the wattage on the appliance label or manual (look for W or kW; 1 kW = 1,000 W).', 'Enter how many hours a day it’s on.', 'Set the average load — 100% for lights and TVs, lower for cycling appliances.', 'Enter your electricity price per kWh from your bill.', 'Read the cost per day, month and year.'],
    formula: { expression: 'Cost = Watts × Hours × Load ÷ 1000 × Price per kWh', explanation: ['Watts × Hours ÷ 1000 gives kWh.', 'Multiply kWh by your tariff to get cost.'] },
    example: { title: 'A 1,500 W space heater, 5 hours a day', steps: ['1,500 × 5 ÷ 1,000 = 7.5 kWh per day.', 'At $0.17 per kWh: 7.5 × 0.17 = $1.28 per day.', 'Over 30 days: about $38.25.'] },
    faqs: [
      { q: 'How do I find my price per kWh?', a: 'Divide the energy charge on your bill by the kWh used, or look for the unit rate on the tariff section. Include taxes and per-kWh delivery charges for a realistic figure.' },
      { q: 'What uses the most electricity at home?', a: 'Heating and cooling are usually the largest loads, followed by water heating, tumble dryers, electric ovens and refrigerators. Small electronics are individually cheap but add up when left on standby.' },
      { q: 'Does an appliance on standby use electricity?', a: 'Yes, typically 0.5–5 W. Enter the standby wattage with 24 hours a day to see its yearly cost.' },
    ],
    related: ['electricity-cost-calculator/ac', 'electricity-cost-calculator/space-heater', 'electricity-cost-calculator/refrigerator', 'percentage-change-calculator'],
  },
  {
    slug: 'electricity-cost-calculator/ac', parent, engine, name: 'AC Electricity Cost Calculator', category: 'energy', popular: true, updated,
    defaults: { watts: 1200, hours: 8, duty: 70, rate: 0.17 },
    title: 'AC Electricity Cost Calculator – Cost to Run an Air Conditioner',
    description: 'How much does your air conditioner cost to run? Calculate AC electricity use and cost per hour, day and month for window, split or central units.',
    lead: 'Estimate how much electricity your air conditioner uses and what it adds to your bill each month.',
    keywords: ['how much electricity does my ac use', 'air conditioner running cost', 'ac cost per hour', 'split ac power consumption', 'window ac watts', 'inverter ac', '1.5 ton ac', 'aircon'],
    about: [
      'Air conditioners are usually the biggest summer electricity load. Typical power draw while the compressor runs: small window units 500–900 W, 1–1.5 ton split units 1,000–1,800 W, and central systems 3,000–5,000 W. Check the rating plate for “rated input power” or “cooling power input”.',
      'The compressor cycles off once the room reaches the set temperature, so the average draw is lower than the label. 60–80% is a fair starting point on hot days; inverter models in mild weather can average much less. The default here is a 1,200 W split unit at 70% load for 8 hours.',
      'Each degree you raise the thermostat typically trims a few percent off cooling energy. Clean filters, shaded outdoor units and closed curtains during the afternoon all reduce how hard the compressor works.',
    ],
    howTo: ['Enter your AC’s input power in watts (not the BTU or cooling capacity).', 'Enter hours of use per day.', 'Keep 70% load for a hot day, or lower it for an inverter unit in mild weather.', 'Enter your price per kWh.'],
    formula: { expression: 'Monthly cost = Watts × Hours × Load ÷ 1000 × 30 × Price', explanation: ['BTU ratings describe cooling output, not electricity use. If you only know the EER, input watts ≈ BTU ÷ EER.'] },
    example: { title: 'A 1.5 ton split AC', steps: ['1,500 W × 8 h × 70% = 8.4 kWh per day.', 'At $0.17/kWh: about $1.43 per day.', 'About $42.84 over a 30-day month.'] },
    faqs: [
      { q: 'How many watts does a 1.5 ton AC use?', a: 'Usually 1,300–1,800 W while the compressor runs, depending on efficiency. Inverter models draw less on average because they slow the compressor rather than switching it off and on.' },
      { q: 'Is it cheaper to leave the AC on all day?', a: 'Usually not. Raising the set point or switching off while you’re out uses less energy overall than holding a low temperature in an empty home, even though cooling back down takes some extra work.' },
      { q: 'Does a higher star or SEER rating really save money?', a: 'Yes — a more efficient unit delivers the same cooling for fewer watts. The saving is largest in hot climates where the AC runs many hours a day.' },
    ],
    related: ['electricity-cost-calculator/ceiling-fan', 'electricity-cost-calculator', 'electricity-cost-calculator/refrigerator', 'electricity-cost-calculator/space-heater'],
  },
  {
    slug: 'electricity-cost-calculator/refrigerator', parent, engine, name: 'Refrigerator Electricity Cost Calculator', category: 'energy', updated,
    defaults: { watts: 150, hours: 24, duty: 35, rate: 0.17 },
    title: 'Refrigerator Running Cost Calculator – Fridge kWh per Year',
    description: 'Calculate how much your fridge or freezer costs to run per day, month and year. Uses realistic compressor cycling so results match real-world usage.',
    lead: 'Work out what your fridge or freezer costs to run, using realistic compressor cycling rather than the label maximum.',
    keywords: ['fridge electricity usage', 'refrigerator kwh per year', 'freezer running cost', 'how much power does a fridge use', 'fridge watts'],
    about: [
      'A refrigerator is plugged in 24 hours a day, but its compressor only runs part of the time — commonly 30–40% in a kitchen at room temperature, more in a hot garage or when the door is opened often. Modern fridges draw about 100–250 W while running.',
      'The most reliable number is the yearly kWh on the energy label (for example 400 kWh/year). Divide it by 365 to get kWh per day; if you enter that as watts × 24 hours at 100% load you get the same result.',
      'Old fridges can use two or three times as much as current models. If yours is 15+ years old, compare its yearly cost here against a new model’s label figure.',
    ],
    howTo: ['Enter the running wattage from the label (or the yearly kWh ÷ 8.76).', 'Keep 24 hours per day.', 'Use 30–40% load for a typical kitchen; raise it for hot rooms.', 'Enter your price per kWh.'],
    formula: { expression: 'kWh per day = Watts × 24 × Load ÷ 1000', explanation: ['Yearly kWh ÷ 365 gives the same figure if you have the energy label.'] },
    example: { title: 'A 150 W fridge running 35% of the time', steps: ['150 × 24 × 0.35 = 1,260 Wh = 1.26 kWh per day.', '1.26 × 365 = 460 kWh per year.', 'At $0.17/kWh: about $78 per year.'] },
    faqs: [
      { q: 'How much electricity does a fridge use per day?', a: 'Most modern fridge-freezers use about 1–2 kWh per day. Large side-by-side models with ice makers can use more.' },
      { q: 'Does a full fridge use less energy?', a: 'A reasonably full fridge holds its temperature better when the door is opened, but packing it so tightly that air can’t circulate makes the compressor work harder.' },
      { q: 'Where should I set the temperature?', a: 'Around 3–4 °C (37–40 °F) for the fridge and −18 °C (0 °F) for the freezer. Colder settings use more energy without improving food safety.' },
    ],
    related: ['electricity-cost-calculator/ac', 'electricity-cost-calculator/tv', 'electricity-cost-calculator', 'electricity-cost-calculator/washing-machine'],
  },
  {
    slug: 'electricity-cost-calculator/space-heater', parent, engine, name: 'Space Heater Cost Calculator', category: 'energy', updated,
    defaults: { watts: 1500, hours: 5, duty: 80, rate: 0.17 },
    title: 'Space Heater Cost Calculator – Cost per Hour & Month',
    description: 'How much does a space heater cost to run? Calculate electric heater cost per hour, day and month for 750 W, 1,500 W or any wattage.',
    lead: 'Find what an electric space heater costs per hour and per month, including thermostat cycling.',
    keywords: ['space heater cost per hour', 'electric heater running cost', '1500 watt heater cost', 'oil filled radiator cost', 'heater electricity'],
    about: [
      'Most plug-in heaters in North America max out at 1,500 W because that is the limit for a standard 15 A outlet; many have a 750 W low setting. In the UK and Europe, 2,000–3,000 W heaters are common.',
      'All resistive electric heaters — fan, oil-filled, ceramic, infrared — turn electricity into heat at essentially 100% efficiency. What differs is how they deliver it. A thermostat will cycle the heater off once the room is warm, which is why the default load is 80%.',
      'Heating one small room with a space heater can be cheaper than running central heat for the whole house. Heating a large, drafty room with one usually is not.',
    ],
    howTo: ['Enter the heater wattage (setting you actually use).', 'Enter the hours per day.', 'Lower the load if the thermostat clicks off often.', 'Enter your electricity price.'],
    formula: { expression: 'Cost per hour = Watts × Load ÷ 1000 × Price', explanation: ['A 1,500 W heater at full power uses 1.5 kWh every hour.'] },
    example: { title: 'A 1,500 W heater for 5 hours', steps: ['1,500 × 5 × 0.8 = 6 kWh per day.', 'At $0.17/kWh: $1.02 per day.', 'About $30.60 per month.'] },
    faqs: [
      { q: 'Are oil-filled radiators cheaper to run than fan heaters?', a: 'Per kWh, no — every electric resistance heater is equally efficient. Oil-filled units release heat more gently and keep radiating after switching off, which can feel more comfortable and cycle less often.' },
      { q: 'Is a heat pump cheaper than a space heater?', a: 'Yes, usually much cheaper. Heat pumps deliver 2–4 units of heat per unit of electricity, compared with 1 for a resistive heater.' },
      { q: 'How much does it cost to run a heater overnight?', a: 'Enter 8 hours. A 1,500 W heater at 60–80% load uses roughly 7–10 kWh overnight.' },
    ],
    related: ['electricity-cost-calculator/ac', 'electricity-cost-calculator/ceiling-fan', 'electricity-cost-calculator', 'electricity-cost-calculator/refrigerator'],
  },
  {
    slug: 'electricity-cost-calculator/ceiling-fan', parent, engine, name: 'Ceiling Fan Electricity Cost Calculator', category: 'energy', updated,
    defaults: { watts: 60, hours: 10, duty: 100, rate: 0.17 },
    title: 'Ceiling Fan Electricity Cost Calculator – Fan Running Cost',
    description: 'Calculate the electricity a ceiling or pedestal fan uses and what it costs per day and month. Compare AC-motor and energy-saving BLDC fans.',
    lead: 'See how little a fan costs to run, and how much a BLDC (DC motor) fan saves over an older model.',
    keywords: ['fan electricity consumption', 'ceiling fan watts', 'bldc fan savings', 'pedestal fan cost', 'fan running cost per month'],
    about: [
      'Conventional ceiling fans with AC induction motors draw about 50–90 W on high. Energy-efficient BLDC (brushless DC) fans draw 25–35 W for similar airflow. Pedestal and table fans range from 20 to 60 W.',
      'Fans don’t cool the air — they make you feel 2–4 °C cooler through evaporation. Running a fan alongside an AC lets you set the thermostat higher, which saves far more than the fan costs.',
      'Try the calculator with 60 W, then with 30 W, to see what a BLDC upgrade saves per fan per year.',
    ],
    howTo: ['Enter the fan wattage on the speed you normally use.', 'Enter hours per day.', 'Keep load at 100% — fans don’t cycle.', 'Enter the number of fans if you want a household total.'],
    formula: { expression: 'Monthly cost = Watts × Hours × Fans ÷ 1000 × 30 × Price', explanation: [] },
    example: { title: 'A 60 W fan running 10 hours a day', steps: ['60 × 10 = 600 Wh = 0.6 kWh per day.', 'At $0.17/kWh: about $0.10 per day.', 'About $3.06 per month.'] },
    faqs: [
      { q: 'Does fan speed affect electricity use?', a: 'Yes. On lower speeds a fan draws noticeably less power — often half or less of its top-speed rating.' },
      { q: 'Is a BLDC fan worth it?', a: 'If the fan runs many hours a day, yes. Saving 30 W over 12 hours a day is about 130 kWh a year per fan.' },
      { q: 'Fan or AC — which is cheaper?', a: 'A fan uses a tiny fraction of an AC’s power — roughly 50 W versus 1,000 W or more.' },
    ],
    related: ['electricity-cost-calculator/ac', 'electricity-cost-calculator/tv', 'electricity-cost-calculator', 'electricity-cost-calculator/space-heater'],
  },
  {
    slug: 'electricity-cost-calculator/tv', parent, engine, name: 'TV Electricity Cost Calculator', category: 'energy', updated,
    defaults: { watts: 90, hours: 5, duty: 100, rate: 0.17 },
    title: 'TV Electricity Cost Calculator – How Much Power Does a TV Use?',
    description: 'Calculate how much electricity your TV uses and costs per day, month and year. Typical wattage for LED, OLED and large-screen TVs explained.',
    lead: 'Estimate your TV’s electricity use and yearly cost, including the effect of screen size and brightness.',
    keywords: ['tv power consumption', 'how many watts does a tv use', 'tv electricity cost', 'oled tv watts', '65 inch tv power'],
    about: [
      'Modern LED TVs typically draw 50–120 W depending on size, while large 65–75 inch models and HDR content can push that to 150–250 W. Older plasma sets were much hungrier.',
      'Brightness is the biggest factor you control. “Vivid” or store-demo picture modes can use far more power than standard or eco modes. Standby is usually under 1 W on recent sets.',
    ],
    howTo: ['Enter the TV’s typical on-mode power from the label or spec sheet.', 'Enter daily viewing hours.', 'Enter your electricity price.'],
    formula: { expression: 'Yearly cost = Watts × Hours × 365 ÷ 1000 × Price', explanation: [] },
    example: { title: 'A 55 inch LED TV at 90 W, 5 hours a day', steps: ['90 × 5 = 450 Wh = 0.45 kWh per day.', 'At $0.17/kWh: about $2.30 per month.', 'About $28 per year.'] },
    faqs: [
      { q: 'Do bigger TVs use more electricity?', a: 'Generally yes — power scales roughly with screen area and brightness. A 75 inch set can use twice as much as a 50 inch one.' },
      { q: 'Does a gaming console add much?', a: 'Yes. Current consoles draw roughly 150–220 W while gaming. Run the calculator again with the console’s wattage and add the two.' },
      { q: 'Should I unplug my TV at night?', a: 'Modern TVs use very little on standby, so the saving is small — usually less than a dollar a year.' },
    ],
    related: ['electricity-cost-calculator/ceiling-fan', 'electricity-cost-calculator/refrigerator', 'electricity-cost-calculator', 'electricity-cost-calculator/washing-machine'],
  },
  {
    slug: 'electricity-cost-calculator/washing-machine', parent, engine, name: 'Washing Machine Electricity Cost Calculator', category: 'energy', updated,
    defaults: { watts: 500, hours: 1, duty: 100, rate: 0.17 },
    title: 'Washing Machine Running Cost Calculator – Cost per Load',
    description: 'Calculate the electricity cost of your washing machine per wash, month and year. Shows why water heating drives the cost and how cold washes save money.',
    lead: 'Estimate what your washing machine costs per cycle and per year — and why the wash temperature matters most.',
    keywords: ['washing machine electricity cost', 'cost per wash', 'washer power consumption', 'washing machine kwh per cycle', 'laundry cost'],
    about: [
      'The motor in a washing machine uses relatively little power. Most of the energy goes into heating water: a 40 °C wash might use 0.5–1 kWh per cycle, while a 60–90 °C cycle can use 1.5–2.5 kWh. Cold washes use a fraction of that.',
      'Machines that take hot water from your boiler or water heater use less electricity themselves, but the heating cost moves to your water heater rather than disappearing.',
      'The default here (500 W average over a 1-hour cycle ≈ 0.5 kWh) is a typical 30–40 °C wash. If your machine’s label lists kWh per cycle, enter that number × 1000 as watts with 1 hour.',
    ],
    howTo: ['Enter the average power, or kWh per cycle × 1000.', 'Enter cycles per day as hours (for example 0.5 for one wash every two days).', 'Enter your electricity price.'],
    formula: { expression: 'Cost per wash = kWh per cycle × Price', explanation: ['Average watts × cycle length in hours ÷ 1000 = kWh per cycle.'] },
    example: { title: 'One 40 °C wash a day', steps: ['About 0.5 kWh per cycle.', 'At $0.17/kWh: about $0.09 per wash.', 'About $31 per year at one wash a day.'] },
    faqs: [
      { q: 'Does washing at 30 °C really save money?', a: 'Yes. Water heating is the main cost, so a 30 °C wash can use well under half the energy of a 60 °C one. Modern detergents are designed to work at low temperatures.' },
      { q: 'Are eco programmes cheaper even though they take longer?', a: 'Usually yes. They soak longer at lower temperatures, which takes more time but less heating energy.' },
      { q: 'What about the tumble dryer?', a: 'Dryers often cost more per load than washing. Run the calculator with your dryer’s wattage (often 2,000–3,000 W) and cycle time.' },
    ],
    related: ['electricity-cost-calculator/refrigerator', 'electricity-cost-calculator/tv', 'electricity-cost-calculator', 'electricity-cost-calculator/space-heater'],
  },
];
