import type { ToolContent } from '../types';

const updated = '2026-10-07';

export const everydayTools: ToolContent[] = [
  {
    slug: 'percentage-calculator', name: 'Percentage Calculator', category: 'everyday', popular: true, updated,
    title: 'Percentage Calculator – X% of Y, What Percent & More',
    description: 'Three percentage calculators in one: find X% of a number, what percent one number is of another, or the whole from a part. Shows the working.',
    lead: 'Answer the three everyday percentage questions — “what is 15% of 240?”, “36 is what percent of 240?” and “36 is 15% of what?”',
    keywords: ['percent', 'percentage of a number', 'what percent is', 'how to calculate percentage', 'percent of total', 'tip', 'grade percentage'],
    about: [
      'Almost every percentage problem is one of three questions, built from the same relationship: part = percentage × whole. Pick the question you are asking from the dropdown and the calculator rearranges the formula for you.',
      'Use it for tips, test scores, tax, commission, survey results or checking whether a “40% off” claim adds up.',
    ],
    howTo: ['Choose the question you want to answer.', 'Fill in the two numbers you know.', 'Read the answer — open “Show the working” to see each step.'],
    formula: { expression: 'Part = Percentage ÷ 100 × Whole', explanation: ['What percent: Percentage = Part ÷ Whole × 100.', 'Find the whole: Whole = Part ÷ (Percentage ÷ 100).'] },
    example: { title: 'A test score', steps: ['You scored 42 out of 60.', '42 ÷ 60 = 0.70.', '0.70 × 100 = 70%.'] },
    faqs: [
      { q: 'How do I work out a percentage of a number in my head?', a: 'Find 10% by moving the decimal point one place left, then scale. 15% of 240: 10% is 24, 5% is 12, so 15% is 36.' },
      { q: 'Is X% of Y the same as Y% of X?', a: 'Yes. 8% of 50 equals 50% of 8 — both are 4. Swap them when one is easier to calculate.' },
      { q: 'How do I calculate percentage increase?', a: 'Use the percentage change calculator: subtract the old value from the new one, divide by the old value and multiply by 100.' },
    ],
    related: ['percentage-change-calculator', 'discount-calculator', 'profit-margin-calculator', 'markup-calculator'],
  },
  {
    slug: 'percentage-change-calculator', name: 'Percentage Increase & Decrease Calculator', category: 'everyday', updated,
    title: 'Percentage Increase / Decrease Calculator',
    description: 'Calculate the percentage increase or decrease between two numbers, the change in value and the percentage difference. Clear formula and examples.',
    lead: 'Compare an old and new value to get the percentage increase or decrease — for prices, salaries, traffic, weight or anything else.',
    keywords: ['percent increase', 'percent decrease', 'percentage change formula', 'growth rate', 'percentage difference', 'price increase'],
    about: [
      'Percentage change measures how much something moved relative to where it started. It is the standard way to report price rises, salary increases, website traffic and sales growth.',
      'Percentage difference is different: it compares two values with no “before” or “after”, using their average as the baseline. Both are shown so you can use whichever fits.',
    ],
    howTo: ['Enter the original (starting) value.', 'Enter the new value.', 'The result is labelled as an increase or a decrease automatically.'],
    formula: { expression: 'Change % = (New − Original) ÷ |Original| × 100', explanation: ['Percentage difference = |A − B| ÷ ((A + B) ÷ 2) × 100.'] },
    example: { title: 'A rent increase', steps: ['Rent goes from $1,200 to $1,350.', '$1,350 − $1,200 = $150.', '$150 ÷ $1,200 = 0.125 → a 12.5% increase.'] },
    faqs: [
      { q: 'Why is a 50% drop followed by a 50% rise not back to the start?', a: 'Each percentage is applied to a different base. $100 down 50% is $50; $50 up 50% is only $75. To recover a 50% drop you need a 100% rise.' },
      { q: 'Can percentage change be more than 100%?', a: 'Yes, for increases. Going from 20 to 70 is a 250% increase. A decrease can never exceed 100%, unless the value turns negative.' },
      { q: 'What if the original value is zero?', a: 'Percentage change is undefined because you cannot divide by zero. Report the absolute change instead.' },
    ],
    related: ['percentage-calculator', 'discount-calculator', 'profit-margin-calculator', 'date-difference-calculator'],
  },
  {
    slug: 'age-calculator', name: 'Age Calculator', category: 'everyday', popular: true, updated,
    title: 'Age Calculator – Exact Age in Years, Months & Days',
    description: 'Calculate your exact age in years, months and days from your date of birth, plus total weeks and days lived and a countdown to your next birthday.',
    lead: 'Get an exact age — years, months and days — on today’s date or any date you choose.',
    keywords: ['how old am i', 'date of birth calculator', 'age on date', 'birthday calculator', 'days old', 'chronological age'],
    about: [
      'Counting age precisely is fiddlier than it looks, because months have different lengths and leap years add an extra day. This calculator counts complete years, then complete months, then the remaining days — the same way age is stated on official forms.',
      'Set the “age on” date to check eligibility on a particular day: school entry cut-offs, visa rules, insurance or retirement dates.',
    ],
    howTo: ['Enter the date of birth.', 'Leave the second date empty for today, or pick a date to calculate age at that point.', 'Read the age, the totals and how long until the next birthday.'],
    formula: { expression: 'Age = completed years + completed months + remaining days', explanation: ['If the day of the month hasn’t been reached yet, borrow the number of days in the previous month.', 'If the month hasn’t been reached yet, borrow 12 months from the years.'] },
    example: { title: 'Born 29 February 2000, on 7 October 2026', steps: ['Years: 2026 − 2000 = 26 (the birthday has passed this year).', 'Months: October − February = 7, but the 29th hasn’t come yet in October → 7 months and some days.', 'Result: 26 years, 7 months, 8 days.'] },
    faqs: [
      { q: 'How is age calculated for a 29 February birthday?', a: 'In non-leap years the calculator treats 1 March as the anniversary for the countdown. Legally, many countries consider the person a year older on 1 March, though some use 28 February.' },
      { q: 'Does it account for time zones?', a: 'Dates are handled as calendar days, so time zones and daylight saving don’t shift the result by a day.' },
      { q: 'How many days old am I?', a: 'See the “Total days” row — it counts every day from your birth date to the chosen date.' },
    ],
    related: ['date-difference-calculator', 'percentage-calculator', 'unix-timestamp-converter', 'percentage-change-calculator'],
  },
  {
    slug: 'date-difference-calculator', name: 'Date Difference Calculator', category: 'everyday', updated,
    title: 'Days Between Dates Calculator – Date Difference',
    description: 'Count the days between two dates, plus weeks, months, years and weekdays. Choose whether to include the end date. Free date difference calculator.',
    lead: 'Count how many days, weeks and weekdays fall between two dates — for deadlines, notice periods, trips and countdowns.',
    keywords: ['days between dates', 'how many days until', 'day counter', 'weeks between dates', 'business days', 'working days'],
    about: [
      'The standard count excludes the end date: from Monday to Friday is 4 days. When you’re counting days of something that happens on both dates — a hotel stay counted in days, or a leave period — switch on “include end date”.',
      'The weekday count skips Saturdays and Sundays. It does not know your public holidays, so subtract those yourself for an exact working-day figure.',
    ],
    howTo: ['Pick the start date.', 'Pick the end date.', 'Decide whether the end date should be counted.', 'Read total days, the breakdown and weekdays.'],
    formula: { expression: 'Days = End date − Start date (+1 if including the end date)', explanation: ['Weekdays are counted one day at a time, excluding Saturdays and Sundays.'] },
    example: { title: 'Days left in the year from 1 Jan 2026', steps: ['Start: 1 January 2026. End: 31 December 2026.', 'Excluding the end date: 364 days.', 'Including it: 365 days — the whole year.'] },
    faqs: [
      { q: 'Should I include the end date?', a: 'Include it when both the first and last day count, like a rental of 1–5 June (5 days). Exclude it for durations, like the time from one date to another (4 days).' },
      { q: 'Does it handle leap years?', a: 'Yes. Dates are calculated from the real calendar, so 29 February is counted in leap years.' },
      { q: 'Can I count backwards?', a: 'Yes — if the end date is before the start date, the dates are swapped and the result is marked.' },
    ],
    related: ['age-calculator', 'unix-timestamp-converter', 'percentage-calculator', 'electricity-cost-calculator'],
  },
];

export const homeTools: ToolContent[] = [
  {
    slug: 'tile-calculator', name: 'Tile Calculator', category: 'home', popular: true, updated,
    title: 'Tile Calculator – How Many Tiles Do I Need?',
    description: 'Calculate how many tiles and boxes you need for a floor or wall, including grout joints and waste. Works in feet/inches or metres/cm, with cost estimate.',
    lead: 'Enter the area and tile size to get the number of tiles, boxes and cost — with grout joints and a waste allowance included.',
    keywords: ['how many tiles', 'tile estimator', 'floor tile calculator', 'wall tile calculator', 'tiles per square foot', 'tile boxes', 'bathroom tiles'],
    about: [
      'Most tile shortfalls come from forgetting two things: the grout joint, which makes each tile cover slightly more area, and waste from cuts, breakages and pattern matching. This calculator includes both.',
      'Buy all your tiles from the same batch (check the lot number on the box). Tiles from different production runs can vary in shade, and returning a spare box is easier than finding a matching one later.',
    ],
    howTo: ['Choose imperial or metric units.', 'Enter the length and width of the area. For L-shaped rooms, split into rectangles and add the results.', 'Enter the tile size and grout joint.', 'Set the waste: 10% for a straight layout, 15% for diagonal or herringbone, 20% for large-format tiles in small rooms.', 'Optionally add tiles per box and box price for a shopping list.'],
    formula: { expression: 'Tiles = Area ÷ ((Tile L + Joint) × (Tile W + Joint)) × (1 + Waste %)', explanation: ['Convert tile size to the same unit as the area first (12 in = 1 ft; 100 cm = 1 m).', 'Always round up — you can’t buy part of a tile.'] },
    example: { title: 'A 12 × 10 ft kitchen with 12 × 12 in tiles', steps: ['Area: 120 sq ft.', 'Each tile with a 1/8 in joint covers about 1.02 sq ft.', '120 ÷ 1.02 ≈ 117.5 tiles, plus 10% waste → 130 tiles.'] },
    faqs: [
      { q: 'How much extra tile should I buy?', a: '10% is standard for straight lays. Add 15% for diagonal, herringbone or rooms with many corners, and keep a few spares for future repairs.' },
      { q: 'Do I subtract the area under cabinets or a bath?', a: 'You can, if the tile won’t go there. Many tilers tile under freestanding units anyway so the floor can be changed later.' },
      { q: 'How many tiles are in a square metre?', a: 'For 30 × 30 cm tiles, about 11 per m² before waste. For 60 × 60 cm tiles, about 2.8 per m².' },
    ],
    related: ['flooring-calculator', 'paint-calculator', 'concrete-calculator', 'gravel-calculator'],
  },
  {
    slug: 'paint-calculator', name: 'Paint Calculator', category: 'home', popular: true, updated,
    title: 'Paint Calculator – How Much Paint Do I Need?',
    description: 'Estimate gallons or litres of paint for a room. Subtracts doors and windows, handles multiple coats and ceilings. Free paint calculator with coverage guide.',
    lead: 'Enter your room size and get the paint you need — walls, optional ceiling, doors and windows subtracted, any number of coats.',
    keywords: ['how much paint', 'gallons of paint', 'paint estimator', 'litres of paint per room', 'paint coverage', 'wall paint'],
    about: [
      'Paint coverage is printed on the can. A typical US gallon of interior paint covers around 350–400 sq ft per coat on smooth, primed walls; in metric, around 10–12 m² per litre. Rough, porous or very dark-to-light colour changes can cut that significantly.',
      'The calculator subtracts a standard door (about 21 sq ft / 1.9 m²) and window (about 15 sq ft / 1.4 m²) for each one you enter. Large patio doors or picture windows should be counted as two.',
    ],
    howTo: ['Pick feet or metres.', 'Enter the room length, width and wall height.', 'Count the doors and windows.', 'Set the number of coats — two is normal for a colour change.', 'Enter your paint’s coverage if it’s on the tin; otherwise the typical value is used.'],
    formula: { expression: 'Paint = (2 × (L + W) × H − openings) × coats ÷ coverage', explanation: ['Add L × W if you are painting the ceiling.', 'Coverage defaults to 350 sq ft per gallon or 10 m² per litre.'] },
    example: { title: 'A 14 × 12 ft bedroom, 8 ft walls, 2 coats', steps: ['Walls: 2 × (14 + 12) × 8 = 416 sq ft.', 'Minus one door and two windows: 416 − 21 − 30 = 365 sq ft.', '365 × 2 coats ÷ 350 = 2.09 gallons → buy 3 gallons, or 2 gallons plus a quart.'] },
    faqs: [
      { q: 'How much does a gallon of paint cover?', a: 'Usually 350–400 sq ft per coat on smooth walls. Textured surfaces, fresh plaster and bare wood soak up more paint, sometimes reducing coverage to 250 sq ft.' },
      { q: 'Do I need two coats?', a: 'Two coats give even colour and better durability, especially when changing colour. One coat can work when refreshing the same colour with a quality paint.' },
      { q: 'Do I need primer?', a: 'Use primer on new drywall or plaster, bare wood, stains, or when going from a dark to a much lighter colour. Primer has its own coverage rate — calculate it as a separate coat.' },
    ],
    related: ['tile-calculator', 'flooring-calculator', 'concrete-calculator', 'gravel-calculator'],
  },
  {
    slug: 'flooring-calculator', name: 'Flooring Calculator', category: 'home', updated,
    title: 'Flooring Calculator – Square Footage, Boxes & Cost',
    description: 'Calculate how much laminate, vinyl plank or hardwood flooring to buy, how many boxes, and the material cost. Includes waste guidance for different layouts.',
    lead: 'Work out the square footage (or m²) of flooring to buy, how many boxes that is, and what it will cost.',
    keywords: ['how much flooring', 'laminate calculator', 'vinyl plank calculator', 'hardwood flooring calculator', 'square footage', 'flooring boxes'],
    about: [
      'Flooring is sold by the box, and each box covers a set area printed on the label. The calculator adds your waste allowance, rounds up to whole boxes and prices the boxes you’ll actually buy — not just the room area.',
      'Measure each room at its widest point and include closets and doorways that will be floored. Leave the material in the room for 48 hours before fitting; most laminate and wood manufacturers require it.',
    ],
    howTo: ['Enter the room length and width.', 'Set waste: 5–7% for simple rectangular rooms, 10% for most rooms, 15% for diagonal installs.', 'Add the coverage per box from the packaging.', 'Add the price per square foot or m² to estimate cost.'],
    formula: { expression: 'Flooring = Length × Width × (1 + Waste %)', explanation: ['Boxes = Flooring ÷ Coverage per box, rounded up.', 'Cost = Boxes × Coverage per box × Price per unit area.'] },
    example: { title: 'A 15 × 12 ft living room', steps: ['Area: 180 sq ft.', 'With 10% waste: 198 sq ft.', 'At 20 sq ft per box: 9.9 → 10 boxes (200 sq ft).'] },
    faqs: [
      { q: 'How much extra flooring should I buy?', a: 'Around 10% for most rooms. Simple rectangles with straight boards can manage 5–7%; herringbone and diagonal layouts need 15% or more.' },
      { q: 'Should I include closets?', a: 'Yes, if they will get the same floor. Measure them separately and add the areas together.' },
      { q: 'Do I need underlayment?', a: 'Most floating laminate and many vinyl floors need underlayment unless it is pre-attached. It is sold by area, so the same square footage applies (without the waste factor).' },
    ],
    related: ['tile-calculator', 'paint-calculator', 'concrete-calculator', 'gravel-calculator'],
  },
  {
    slug: 'concrete-calculator', name: 'Concrete Calculator', category: 'home', popular: true, updated,
    title: 'Concrete Calculator – Cubic Yards & Bags for a Slab',
    description: 'Calculate concrete for a slab, patio or footing in cubic yards, cubic metres and number of 80 lb, 60 lb or 25 kg bags. Includes extra for spillage.',
    lead: 'Get the volume of concrete for a slab or patio, and how many premix bags or cubic yards to order.',
    keywords: ['how much concrete', 'cubic yards of concrete', 'concrete bags', '80 lb bags', 'slab calculator', 'patio concrete', 'cubic meters'],
    about: [
      'Concrete is ordered by volume — cubic yards in the US, cubic metres elsewhere. For small jobs you’ll buy premixed bags instead; an 80 lb bag yields about 0.60 cubic feet and a 60 lb bag about 0.45 cubic feet once mixed.',
      'Order 5–10% more than the exact volume. Sub-bases are never perfectly flat, forms bow slightly, and running short in the middle of a pour leaves a weak cold joint.',
    ],
    howTo: ['Choose feet/inches or metres/cm.', 'Enter the slab length and width.', 'Enter the thickness: 4 in (10 cm) for patios and paths, 5–6 in (12–15 cm) for driveways.', 'Keep 10% extra unless your base is laser-levelled.'],
    formula: { expression: 'Volume = Length × Width × Thickness', explanation: ['Imperial: ft × ft × (in ÷ 12) = cubic feet; ÷ 27 = cubic yards.', 'Bags = cubic feet ÷ yield per bag, rounded up.'] },
    example: { title: 'A 10 × 10 ft patio, 4 in thick', steps: ['10 × 10 × (4 ÷ 12) = 33.3 cubic feet.', '33.3 ÷ 27 = 1.23 cubic yards (before extra).', 'With 10% extra: 36.7 cu ft → 62 bags of 80 lb, or about 1.36 yd³ ready-mix.'] },
    faqs: [
      { q: 'How many 80 lb bags make a yard of concrete?', a: 'About 45 bags (27 cu ft ÷ 0.60). For more than about one cubic yard, ready-mix delivery is usually cheaper and much less work.' },
      { q: 'How thick should a concrete slab be?', a: 'Four inches is standard for patios, walkways and shed bases. Driveways that take cars usually need 5–6 inches, and heavier vehicles more, plus reinforcement.' },
      { q: 'How long before I can walk or drive on it?', a: 'Typically walkable after 24–48 hours and drivable after about 7 days. Concrete reaches its design strength around 28 days.' },
    ],
    related: ['gravel-calculator', 'tile-calculator', 'flooring-calculator', 'paint-calculator'],
  },
  {
    slug: 'gravel-calculator', name: 'Gravel Calculator', category: 'home', updated,
    title: 'Gravel Calculator – Tons & Cubic Yards Needed',
    description: 'Calculate how much gravel, crushed stone, river rock or sand you need in tons and cubic yards (or tonnes and m³) for a driveway, path or garden bed.',
    lead: 'Turn the size and depth of a driveway, path or garden bed into tons and cubic yards of gravel.',
    keywords: ['how much gravel', 'gravel tons', 'crushed stone calculator', 'driveway gravel', 'pea gravel', 'cubic yards to tons', 'landscape rock'],
    about: [
      'Suppliers sell gravel by weight (tons) or by volume (cubic yards), and the conversion depends on the material. Most gravels weigh 1.2–1.5 tons per cubic yard; the calculator lets you pick a material so the tonnage matches what the yard will load.',
      'Depth matters more than people expect: 2–3 inches for a decorative path, 4 inches for a patio base, and 4–8 inches for a driveway built in compacted layers. Compaction reduces volume, so buy a little extra for compacted bases.',
    ],
    howTo: ['Choose units.', 'Enter the length and width of the area.', 'Enter the depth.', 'Choose the material to convert volume into weight.'],
    formula: { expression: 'Tons = Length × Width × Depth ÷ 27 × Density', explanation: ['Volume in cubic yards = cubic feet ÷ 27.', 'Density is tons per cubic yard (≈1.4 for typical gravel).'] },
    example: { title: 'A 20 × 10 ft path, 3 in deep', steps: ['20 × 10 × (3 ÷ 12) = 50 cubic feet.', '50 ÷ 27 = 1.85 cubic yards.', '1.85 × 1.4 = 2.6 tons of gravel.'] },
    faqs: [
      { q: 'How many tons are in a cubic yard of gravel?', a: 'Roughly 1.4 tons for typical gravel, but anywhere from 1.2 to 1.5 depending on stone type and moisture. Ask your supplier for their figure.' },
      { q: 'How deep should driveway gravel be?', a: 'Plan for 4–8 inches in layers: a coarse compacted base, then a finer top layer. Soft ground may need geotextile fabric underneath.' },
      { q: 'How much does a ton of gravel cover?', a: 'At 1.4 tons per cubic yard, one ton covers about 115 sq ft at 2 inches deep, or about 77 sq ft at 3 inches.' },
    ],
    related: ['concrete-calculator', 'tile-calculator', 'flooring-calculator', 'paint-calculator'],
  },
];
