import type { ToolContent } from '../types';

const updated = '2026-10-08';

export const fitnessTools: ToolContent[] = [
  {
    slug: 'bmi-calculator', name: 'BMI Calculator', category: 'fitness', popular: true, updated,
    title: 'BMI Calculator – Body Mass Index for Adults',
    description: 'Free BMI calculator: enter your height and weight in lb/ft or kg/cm to get your body mass index, WHO category and healthy weight range.',
    lead: 'Enter your height and weight to get your body mass index, the adult category it falls in and the healthy weight range for your height.',
    keywords: ['body mass index', 'bmi chart', 'healthy weight', 'overweight', 'bmi formula', 'am i overweight'],
    about: [
      'Body mass index compares your weight to your height. It is a quick screening number used by doctors and public-health bodies, not a diagnosis: it cannot tell muscle from fat, so very muscular people often score as “overweight” while being lean.',
      'The categories used here are the World Health Organization adult ranges. They do not apply to children and teenagers, whose BMI is judged against age- and sex-specific percentiles, and some health bodies use lower cut-offs for people of Asian descent.',
    ],
    howTo: ['Choose US or metric units.', 'Enter your weight.', 'Enter your height in feet and inches, or centimetres.', 'Read your BMI, its category and the weight range that gives a BMI of 18.5–24.9 at your height.'],
    formula: { expression: 'BMI = weight (kg) ÷ height (m)²', explanation: ['In US units: BMI = 703 × weight (lb) ÷ height (in)².', 'Under 18.5 underweight · 18.5–24.9 healthy · 25–29.9 overweight · 30 and above obesity.'] },
    example: { title: '170 lb at 5 ft 10 in', steps: ['170 lb = 77.1 kg; 70 in = 1.778 m.', '1.778² = 3.161.', '77.1 ÷ 3.161 = 24.4 → healthy weight range.'] },
    faqs: [
      { q: 'Is BMI accurate for athletes?', a: 'Not very. BMI only uses height and weight, so muscle counts the same as fat. A body fat estimate or waist measurement says more for muscular people.' },
      { q: 'Does BMI work for children?', a: 'No. Under-18s are assessed with BMI-for-age percentile charts, because healthy body composition changes as children grow.' },
      { q: 'What is a healthy BMI?', a: 'For most adults, 18.5 to 24.9. Your doctor may use a different target depending on age, ethnicity and health history.' },
    ],
    related: ['ideal-weight-calculator', 'body-fat-calculator', 'tdee-calculator', 'bmr-calculator'],
  },
  {
    slug: 'bmr-calculator', name: 'BMR Calculator', category: 'fitness', updated,
    title: 'BMR Calculator – Basal Metabolic Rate (Mifflin-St Jeor)',
    description: 'BMR calculator: find how many calories your body burns at complete rest using the Mifflin-St Jeor and Harris-Benedict equations.',
    lead: 'Estimate your basal metabolic rate — the calories your body uses at complete rest just to stay alive — from your age, sex, height and weight.',
    keywords: ['basal metabolic rate', 'resting metabolic rate', 'rmr', 'mifflin st jeor', 'harris benedict', 'calories at rest'],
    about: [
      'Your BMR covers breathing, circulation, temperature control and cell repair. For most people it is the largest part of daily energy use — often 60–70% — even before any movement or exercise.',
      'The calculator uses the Mifflin-St Jeor equation, which studies have found to be the most accurate of the common formulas for most adults, and shows the revised Harris-Benedict result alongside. Both are population estimates; your real figure can differ by 10% or more.',
    ],
    howTo: ['Choose units and sex.', 'Enter age, weight and height.', 'Read your BMR. To include daily activity, use the TDEE calculator.'],
    formula: { expression: 'BMR = 10 × kg + 6.25 × cm − 5 × age + 5 (men) or − 161 (women)', explanation: ['This is the Mifflin-St Jeor equation (1990).', 'Revised Harris-Benedict (men): 88.362 + 13.397 × kg + 4.799 × cm − 5.677 × age.'] },
    example: { title: 'A 30-year-old man, 80 kg, 180 cm', steps: ['10 × 80 = 800.', '6.25 × 180 = 1,125.', '5 × 30 = 150.', '800 + 1,125 − 150 + 5 = 1,780 kcal a day.'] },
    faqs: [
      { q: 'What is the difference between BMR and TDEE?', a: 'BMR is energy at complete rest. TDEE adds everything else — walking, work, exercise and digesting food — so it is always higher.' },
      { q: 'Should I eat my BMR in calories?', a: 'Eating at or below BMR is a very low intake for most people. Plan from your TDEE instead, and get medical advice before any very-low-calorie diet.' },
      { q: 'Does muscle raise BMR?', a: 'Yes, modestly. Lean tissue uses more energy than fat at rest, which is why the formulas use weight and why strength training helps maintain metabolism with age.' },
    ],
    related: ['tdee-calculator', 'macro-calculator', 'bmi-calculator', 'protein-calculator'],
  },
  {
    slug: 'tdee-calculator', name: 'TDEE Calculator', category: 'fitness', popular: true, updated,
    title: 'TDEE Calculator – Daily Calories to Maintain, Lose or Gain',
    description: 'TDEE calculator: estimate your total daily energy expenditure and the calories to maintain, lose or gain weight, based on your activity level.',
    lead: 'Find your total daily energy expenditure — how many calories you burn on an average day — and sensible targets for losing or gaining weight.',
    keywords: ['calorie calculator', 'maintenance calories', 'calories per day', 'calorie deficit', 'how many calories should i eat', 'total daily energy expenditure'],
    about: [
      'TDEE is your BMR multiplied by an activity factor. It is the number of calories that, on average, keeps your weight stable. Eating about 500 kcal a day below it leads to roughly 0.5 kg (1 lb) of weight loss a week for many people; eating slightly above it supports muscle gain when combined with training.',
      'Treat the result as a starting point. Track your weight for two to three weeks, and if it moves differently than expected, adjust intake by 100–200 kcal. Targets below 1,200 kcal (women) or 1,500 kcal (men) are not shown, because very low intakes should be supervised by a professional.',
    ],
    howTo: ['Enter sex, age, weight and height.', 'Pick the activity level that matches a typical week — most people overestimate this, so choose the lower option if unsure.', 'Read your maintenance calories and the targets for gentle loss or gain.'],
    formula: { expression: 'TDEE = BMR × activity factor', explanation: ['Factors: 1.2 sedentary, 1.375 light, 1.55 moderate, 1.725 very active, 1.9 extra active.', 'BMR is calculated with the Mifflin-St Jeor equation.'] },
    example: { title: 'Moderately active man, 30, 80 kg, 180 cm', steps: ['BMR = 1,780 kcal.', 'TDEE = 1,780 × 1.55 = 2,759 kcal a day.', 'Weight-loss target ≈ 2,259 kcal (−500).'] },
    faqs: [
      { q: 'How accurate is a TDEE calculator?', a: 'It is an estimate, typically within about 10% for most people. Your actual weight trend over a few weeks is the best way to fine-tune it.' },
      { q: 'Which activity level should I choose?', a: 'Count only planned exercise and your job. If you sit most of the day and train three times a week, “light” or “moderate” is usually right.' },
      { q: 'How fast should I lose weight?', a: 'Many guidelines suggest about 0.5–1 kg (1–2 lb) a week at most. Slower loss is easier to sustain and helps keep muscle.' },
    ],
    related: ['bmr-calculator', 'macro-calculator', 'protein-calculator', 'bmi-calculator'],
  },
  {
    slug: 'macro-calculator', name: 'Macro Calculator', category: 'fitness', updated,
    title: 'Macro Calculator – Protein, Carbs & Fat in Grams',
    description: 'Macro calculator: split your daily calories into grams of protein, carbs and fat, with per-meal amounts. Balanced, high-protein and low-carb presets.',
    lead: 'Turn a daily calorie target into grams of protein, carbohydrate and fat — per day and per meal.',
    keywords: ['macros', 'macronutrients', 'iifym', 'protein carbs fat', 'macro split', 'keto macros'],
    about: [
      'Macronutrients are the three nutrients that supply calories: protein and carbohydrate give 4 kcal per gram, fat gives 9. A macro split is simply how your daily calories are shared between them.',
      'There is no single best split. Higher protein helps with fullness and keeping muscle while losing fat; endurance athletes usually do better with more carbohydrate. Start with the balanced preset and adjust to what you can stick with.',
    ],
    howTo: ['Enter your daily calorie target (from the TDEE calculator if you don’t have one).', 'Choose a macro split.', 'Set how many meals you eat to see grams per meal.'],
    formula: { expression: 'Grams = Calories × share ÷ kcal per gram', explanation: ['Protein and carbohydrate: 4 kcal per gram.', 'Fat: 9 kcal per gram.'] },
    example: { title: '2,000 kcal on a balanced 30/40/30 split', steps: ['Protein: 2,000 × 30% ÷ 4 = 150 g.', 'Carbs: 2,000 × 40% ÷ 4 = 200 g.', 'Fat: 2,000 × 30% ÷ 9 = 67 g.'] },
    faqs: [
      { q: 'What macro split is best for fat loss?', a: 'Calories matter most for fat loss. Within that, a higher protein share (30–40%) helps with fullness and keeping muscle.' },
      { q: 'Do I need to hit my macros exactly?', a: 'No. Being within about 5–10 g of each target over the week is plenty for most goals.' },
      { q: 'Is alcohol a macro?', a: 'Alcohol provides 7 kcal per gram but no nutrients, so it is usually counted against your carb or fat allowance.' },
    ],
    related: ['tdee-calculator', 'protein-calculator', 'bmr-calculator', 'percentage-calculator'],
  },
  {
    slug: 'body-fat-calculator', name: 'Body Fat Calculator', category: 'fitness', updated,
    title: 'Body Fat Calculator – US Navy Tape-Measure Method',
    description: 'Body fat calculator using the US Navy method: estimate body fat percentage from height, neck, waist and hip measurements, plus fat and lean mass.',
    lead: 'Estimate your body fat percentage with a tape measure, using the same circumference method the US Navy uses.',
    keywords: ['body fat percentage', 'navy body fat', 'body fat estimate', 'lean body mass', 'fat mass', 'tape measure body fat'],
    about: [
      'The US Navy method estimates body fat from a few circumference measurements and your height. It is typically within a few percentage points of lab methods for most people, which makes it a useful way to track change over time without special equipment.',
      'Measure on bare skin, relaxed, at the same time of day each time. Small errors in the waist measurement move the result noticeably, so take each measurement twice and use the average.',
    ],
    howTo: ['Choose units and sex.', 'Enter height, neck and waist (and hips for women).', 'Optionally add weight to see fat mass and lean mass.', 'Re-measure every 2–4 weeks to track progress.'],
    formula: { expression: 'Men: 495 ÷ (1.0324 − 0.19077·log10(waist − neck) + 0.15456·log10(height)) − 450', explanation: ['Women: 495 ÷ (1.29579 − 0.35004·log10(waist + hip − neck) + 0.22100·log10(height)) − 450.', 'All measurements in centimetres.'] },
    example: { title: 'Man, 178 cm, neck 38 cm, waist 86 cm', steps: ['waist − neck = 48 cm.', 'log10(48) = 1.681; log10(178) = 2.250.', '495 ÷ (1.0324 − 0.3207 + 0.3478) − 450 = 17.2% body fat.'] },
    faqs: [
      { q: 'How accurate is the Navy method?', a: 'It usually lands within about 3–4 percentage points of DEXA scans, and is more consistent when the same person takes the measurements the same way.' },
      { q: 'What is a healthy body fat percentage?', a: 'The American Council on Exercise lists 14–24% as fitness-to-average for men and 21–31% for women. Essential fat is about 2–5% for men and 10–13% for women.' },
      { q: 'Where exactly do I measure my waist?', a: 'Men measure horizontally at the navel; women at the narrowest point of the waist. Don’t pull the tape tight or hold your breath.' },
    ],
    related: ['bmi-calculator', 'ideal-weight-calculator', 'tdee-calculator', 'protein-calculator'],
  },
  {
    slug: 'one-rep-max-calculator', name: 'One Rep Max Calculator', category: 'fitness', popular: true, updated,
    title: 'One Rep Max Calculator – Estimate Your 1RM',
    description: 'One rep max calculator: estimate your 1RM from any set of 1–15 reps with the Epley and Brzycki formulas, plus a 60–95% training-weight table.',
    lead: 'Estimate the most you could lift for one rep from a lighter set you have already done — no risky max attempts needed.',
    keywords: ['1rm calculator', 'one rep max', 'max lift', 'bench press max', 'squat max', 'epley formula', 'brzycki formula'],
    about: [
      'Testing a true one-rep max is tiring and carries injury risk. Rep-max formulas estimate it from a hard set of several reps, and most strength programs prescribe working weights as a percentage of that 1RM.',
      'Estimates are most reliable from sets of 2–10 reps taken close to failure with good form. The calculator averages the Epley and Brzycki formulas, which agree closely in that range.',
    ],
    howTo: ['Enter the weight you lifted and choose lb or kg.', 'Enter how many clean reps you completed.', 'Read your estimated 1RM and the training weights at 60–95%.'],
    formula: { expression: 'Epley: 1RM = w × (1 + reps ÷ 30) · Brzycki: 1RM = w × 36 ÷ (37 − reps)', explanation: ['The result shown is the average of both.', 'With 1 rep, the weight lifted is the 1RM.'] },
    example: { title: '100 kg for 5 reps', steps: ['Epley: 100 × (1 + 5/30) = 116.7 kg.', 'Brzycki: 100 × 36 ÷ 32 = 112.5 kg.', 'Average ≈ 115 kg.'] },
    faqs: [
      { q: 'How many reps give the best estimate?', a: 'Sets of about 3–6 reps to near-failure tend to give the most accurate estimates. Above 10–12 reps, endurance starts to skew the result.' },
      { q: 'Does it work for every exercise?', a: 'It works best for big barbell lifts like squat, bench press and deadlift. It is less reliable for small isolation exercises and machines.' },
      { q: 'What percentage of 1RM should I train at?', a: 'Roughly 80–90% for strength (3–6 reps), 65–80% for muscle growth (6–12 reps) and below 65% for technique and endurance work.' },
    ],
    related: ['protein-calculator', 'tdee-calculator', 'kg-to-lbs', 'percentage-calculator'],
  },
  {
    slug: 'protein-calculator', name: 'Protein Calculator', category: 'fitness', updated,
    title: 'Protein Calculator – How Much Protein Per Day?',
    description: 'Protein calculator: how much protein you need per day and per meal for your weight and goal, from the RDA to muscle gain and fat loss.',
    lead: 'Work out a daily protein target from your body weight and goal, split across your meals.',
    keywords: ['protein intake', 'how much protein', 'protein per day', 'protein for muscle gain', 'grams of protein', 'protein per kg'],
    about: [
      'The RDA of 0.8 g of protein per kg of body weight is the minimum to avoid deficiency for sedentary adults. Research on people who train regularly supports higher intakes: about 1.6–2.2 g/kg to build muscle, and similar or slightly higher while losing fat to protect lean mass.',
      'Spreading protein over 3–5 meals of roughly 20–40 g each is a practical way to reach the total. People with kidney disease should follow their doctor’s protein advice rather than these ranges.',
    ],
    howTo: ['Choose units and enter your body weight.', 'Pick the goal closest to yours.', 'Set your number of meals to see grams per meal.'],
    formula: { expression: 'Protein (g/day) = body weight (kg) × g/kg for your goal', explanation: ['Sedentary: 0.8 g/kg · regular exercise: 1.1–1.4 · muscle gain: 1.6–2.2 · fat loss: 1.8–2.4 · endurance: 1.2–1.6.'] },
    example: { title: '80 kg person building muscle', steps: ['80 × 1.6 = 128 g.', '80 × 2.2 = 176 g.', 'Over 4 meals: 32–44 g per meal.'] },
    faqs: [
      { q: 'Can you eat too much protein?', a: 'For healthy adults, intakes up to about 2 g/kg are well studied and considered safe. Very high intakes mainly crowd out other foods.' },
      { q: 'Should I use my current or goal weight?', a: 'If you carry a lot of excess body fat, use your goal weight or lean body mass, otherwise the target will be unrealistically high.' },
      { q: 'Do protein shakes count?', a: 'Yes — protein is protein. Shakes are simply a convenient way to reach the total when meals fall short.' },
    ],
    related: ['macro-calculator', 'tdee-calculator', 'one-rep-max-calculator', 'body-fat-calculator'],
  },
  {
    slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', category: 'fitness', updated,
    title: 'Ideal Weight Calculator – By Height & Sex',
    description: 'Ideal weight calculator: see your ideal body weight by height and sex from the Devine, Robinson, Miller and Hamwi formulas plus the healthy BMI range.',
    lead: 'See the ideal body weight for your height from four classic formulas, alongside the healthy BMI range.',
    keywords: ['ideal body weight', 'ibw', 'healthy weight for height', 'devine formula', 'weight for height chart', 'how much should i weigh'],
    about: [
      'Ideal body weight formulas were created for medical use — the Devine formula, for example, to dose medicines. They give a single number for a height, so the calculator shows the range across four formulas and the broader healthy-BMI range, which is a better everyday guide.',
      'None of these account for frame size, muscle or age. Use them as a reference point, not a target you must hit.',
    ],
    howTo: ['Choose units and sex.', 'Enter your height.', 'Compare the formula range with the healthy BMI range.'],
    formula: { expression: 'Devine: 50 kg (men) or 45.5 kg (women) + 2.3 kg per inch over 5 ft', explanation: ['Robinson: 52 / 49 kg + 1.9 / 1.7 kg per inch.', 'Miller: 56.2 / 53.1 kg + 1.41 / 1.36 kg per inch.', 'Hamwi: 48 / 45.5 kg + 2.7 / 2.2 kg per inch.'] },
    example: { title: 'Man, 5 ft 10 in', steps: ['10 inches over 5 ft.', 'Devine: 50 + 2.3 × 10 = 73 kg (161 lb).', 'Healthy BMI range at this height: 58.5–78.7 kg.'] },
    faqs: [
      { q: 'Which ideal weight formula is most accurate?', a: 'None is “accurate” for an individual; they disagree by several kilograms. The healthy BMI range is the most widely used guide.' },
      { q: 'Does it work for short heights?', a: 'The formulas are defined from 5 ft (152 cm) upward. Below that, use the healthy BMI range.' },
      { q: 'Should athletes use these numbers?', a: 'Not really. Muscular people often weigh more than these formulas suggest while being very lean; body fat percentage is a better measure.' },
    ],
    related: ['bmi-calculator', 'body-fat-calculator', 'tdee-calculator', 'kg-to-lbs'],
  },
];
